%% =========================================================================
%  PROJECT: INVERTED PENDULUM DIGITAL TWIN & OPTIMAL CONTROL SUITE
%  FILE: build_simulink_model.m
%  PURPOSE: Programmatically builds, wires, and saves the algebraic-loop-free
%           multi-rate SIL Simulink model.
% =========================================================================
clear; clc; close all;
system_params; % Load system parameters, LQR gain K, and pre-compensator N_bar

model_name = 'inverted_pendulum_digital_twin';

% 1. Cleanly close and overwrite if already open in memory or disk
if bdIsLoaded(model_name)
    close_system(model_name, 0);
end
if exist([model_name, '.slx'], 'file') == 4
    delete([model_name, '.slx']);
end

% 2. Create and open new Simulink model canvas
new_system(model_name);
open_system(model_name);

% 3. Configure Fixed-Step Continuous/Discrete Hybrid Solver Settings
set_param(model_name, 'SolverType', 'Fixed-step');
set_param(model_name, 'Solver', 'ode4');
set_param(model_name, 'FixedStep', '0.001');
set_param(model_name, 'StopTime', '6.0');
set_param(model_name, 'SaveTime', 'on', 'TimeSaveName', 'tout');
set_param(model_name, 'SaveOutput', 'on', 'OutputSaveName', 'yout');

fprintf('1/4: Initializing Simulink Canvas for %s.slx...\n', model_name);

%% 4. ADD NON-LINEAR PHYSICS DERIVATIVE BLOCK & CONTINUOUS INTEGRATOR
deriv_blk = [model_name, '/Nonlinear_Derivatives'];
add_block('simulink/User-Defined Functions/MATLAB Function', deriv_blk, ...
    'Position', [530, 200, 650, 270]);

deriv_script = sprintf([...
    'function x_dot = Nonlinear_Derivatives(u_force, d_dist, x_state)\n', ...
    '%% Nominal physical parameters\n', ...
    'M = 1.50; m = 0.25; l = 0.35; I = 0.010208; b = 0.10; c = 0.005; g = 9.81;\n', ...
    '\n', ...
    'x_dot_val = x_state(2);\n', ...
    'th        = x_state(3);\n', ...
    'th_dot    = x_state(4);\n', ...
    '\n', ...
    'F_total = u_force + d_dist;\n', ...
    'sin_t = sin(th);\n', ...
    'cos_t = cos(th);\n', ...
    'D = (M + m)*(I + m*l^2) - (m*l*cos_t)^2;\n', ...
    '\n', ...
    'term1 = F_total - b*x_dot_val + m*l*(th_dot^2)*sin_t;\n', ...
    'term2 = m*g*l*sin_t - c*th_dot;\n', ...
    '\n', ...
    'x_ddot  = ((I + m*l^2)*term1 - m*l*cos_t*term2) / D;\n', ...
    'th_ddot = ((M + m)*term2 - m*l*cos_t*term1) / D;\n', ...
    '\n', ...
    'x_dot = [x_dot_val; x_ddot; th_dot; th_ddot];\n', ...
    'end']);

% Inject derivative script via Stateflow root API
sf = sfroot;
chart_deriv = sf.find('Path', deriv_blk, '-isa', 'Stateflow.EMChart');
if ~isempty(chart_deriv)
    chart_deriv.Script = deriv_script;
end

% Continuous Integrator Block (Initial 5-degree tilt error = 0.087266 rad)
add_block('simulink/Continuous/Integrator', [model_name, '/Continuous_Integrator'], ...
    'InitialCondition', '[0.0; 0.0; 0.087266; 0.0]', ...
    'Position', [690, 220, 725, 250]);

%% 5. ADD SENSOR NOISE & DISCRETE ZERO-ORDER HOLD (ADC SAMPLING)
add_block('simulink/Signal Routing/Demux', [model_name, '/State_Demux'], ...
    'Outputs', '4', 'Position', [760, 205, 765, 265]);

add_block('simulink/Sources/Band-Limited White Noise', [model_name, '/Noise_Pos'], ...
    'Cov', '2.5e-5', 'Ts', '0.005', 'Position', [780, 150, 810, 180]);
add_block('simulink/Sources/Band-Limited White Noise', [model_name, '/Noise_Ang'], ...
    'Cov', '3.7e-5', 'Ts', '0.005', 'Position', [780, 290, 810, 320]);

add_block('simulink/Math Operations/Add', [model_name, '/Add_Noise_Pos'], ...
    'Position', [840, 165, 860, 195]);
add_block('simulink/Math Operations/Add', [model_name, '/Add_Noise_Ang'], ...
    'Position', [840, 275, 860, 305]);

add_block('simulink/Math Operations/Matrix Concatenate', [model_name, '/Mux_Meas'], ...
    'NumInputs', '2', 'Mode', 'Vector', 'Position', [890, 215, 900, 260]);

% Discrete ADC Zero-Order Hold at 200 Hz (5 ms)
add_block('simulink/Discrete/Zero-Order Hold', [model_name, '/ZOH_ADC'], ...
    'SampleTime', '0.005', 'Position', [930, 225, 960, 255]);

%% 6. ADD DISCRETE UNIT DELAY (BREAKS ALGEBRAIC LOOP) & EKF OBSERVER
add_block('simulink/Discrete/Unit Delay', [model_name, '/Unit_Delay_U'], ...
    'InitialCondition', '0.0', 'SampleTime', '0.005', ...
    'Position', [450, 380, 485, 410]);

ekf_blk = [model_name, '/Discrete_EKF_Observer'];
add_block('simulink/User-Defined Functions/MATLAB Function', ekf_blk, ...
    'Position', [540, 340, 700, 430]);

ekf_script = sprintf([...
    'function x_hat = Discrete_EKF_Observer(y_meas, u_applied)\n', ...
    'persistent x_est P_cov;\n', ...
    'Ts = 0.005;\n', ...
    'if isempty(x_est)\n', ...
    '    x_est = [0.0; 0.0; 0.0; 0.0];\n', ...
    '    P_cov = diag([0.01, 0.1, 0.005, 0.05]);\n', ...
    'end\n', ...
    'M = 1.50; m = 0.25; l = 0.35; I = 0.010208; b = 0.10; c = 0.005; g = 9.81;\n', ...
    'Q_d = diag([1e-6, 1e-4, 7.6e-7, 7.6e-5]);\n', ...
    'R_d = diag([2.5e-5, 3.7e-5]);\n', ...
    '\n', ...
    '%% 1. State Prediction\n', ...
    'x_dot = [x_est(2);\n', ...
    '         (-(I+m*l^2)*b*x_est(2) + m^2*g*l^2*x_est(3) - m*l*c*x_est(4) + (I+m*l^2)*u_applied) / 0.063802;\n', ...
    '         x_est(4);\n', ...
    '         (m*l*b*x_est(2) + (M+m)*m*g*l*x_est(3) - (M+m)*c*x_est(4) - m*l*u_applied) / 0.063802];\n', ...
    'x_pred = x_est + Ts * x_dot;\n', ...
    '\n', ...
    '%% 2. System Jacobian Phi\n', ...
    'F_mat = [0, 1, 0, 0;\n', ...
    '         0, -0.0640, 1.1771, -0.0069;\n', ...
    '         0, 0, 0, 1;\n', ...
    '         0, 0.1371, 23.5440, -0.1371];\n', ...
    'Phi = eye(4) + F_mat * Ts;\n', ...
    'P_pred = Phi * P_cov * Phi'' + Q_d;\n', ...
    '\n', ...
    '%% 3. Measurement Update\n', ...
    'H = [1, 0, 0, 0; 0, 0, 1, 0];\n', ...
    'S = H * P_pred * H'' + R_d;\n', ...
    'K = (P_pred * H'') / S;\n', ...
    'y_res = y_meas - H * x_pred;\n', ...
    'x_est = x_pred + K * y_res;\n', ...
    'I_KH = eye(4) - K * H;\n', ...
    'P_cov = I_KH * P_pred * I_KH'' + K * R_d * K'';\n', ...
    'x_hat = x_est;\n', ...
    'end']);

chart_ekf = sf.find('Path', ekf_blk, '-isa', 'Stateflow.EMChart');
if ~isempty(chart_ekf)
    chart_ekf.Script = ekf_script;
end

fprintf('2/4: Physics dynamics and discrete EKF observer instantiated...\n');

%% 7. ADD CONTROLLER & REFERENCE GENERATOR BLOCKS
add_block('simulink/Sources/Step', [model_name, '/Reference_Step'], ...
    'Time', '1.0', 'Before', '0.0', 'After', '0.5', 'SampleTime', '0.005', ...
    'Position', [60, 185, 100, 215]);

add_block('simulink/Math Operations/Gain', [model_name, '/N_bar_Gain'], ...
    'Gain', num2str(N_bar), 'Position', [160, 185, 230, 215]);

add_block('simulink/Math Operations/Gain', [model_name, '/LQR_K_Gain'], ...
    'Gain', mat2str(-K_lqr), 'Multiplication', 'Matrix(K*u)', ...
    'Position', [260, 270, 350, 300]);

add_block('simulink/Math Operations/Add', [model_name, '/Add_Control'], ...
    'Position', [390, 185, 410, 235]);

add_block('simulink/Discontinuities/Saturation', [model_name, '/Actuator_Saturation'], ...
    'UpperLimit', '25.0', 'LowerLimit', '-25.0', 'Position', [450, 195, 480, 225]);

add_block('simulink/Sources/Pulse Generator', [model_name, '/Disturbance_Kick'], ...
    'PulseType', 'Time based', 'Period', '10.0', 'PulseWidth', '1.0', ...
    'Amplitude', '0.0', 'PhaseDelay', '3.0', 'Position', [450, 245, 485, 275]);

%% 8. ADD WORKSPACE LOGGING BLOCKS
add_block('simulink/Sinks/To Workspace', [model_name, '/Log_States'], ...
    'VariableName', 'sim_states', 'SaveFormat', 'Array', 'SampleTime', '0.001', ...
    'Position', [770, 120, 840, 150]);

add_block('simulink/Sinks/To Workspace', [model_name, '/Log_Force'], ...
    'VariableName', 'sim_force', 'SaveFormat', 'Array', 'SampleTime', '0.001', ...
    'Position', [520, 130, 590, 160]);

add_block('simulink/Sinks/To Workspace', [model_name, '/Log_EKF'], ...
    'VariableName', 'sim_ekf', 'SaveFormat', 'Array', 'SampleTime', '0.005', ...
    'Position', [760, 370, 830, 400]);

fprintf('3/4: All SIL blocks placed on canvas...\n');

%% 9. ROUTE SIGNAL LINES
% Reference & Control path
add_line(model_name, 'Reference_Step/1', 'N_bar_Gain/1');
add_line(model_name, 'N_bar_Gain/1', 'Add_Control/1');
add_line(model_name, 'LQR_K_Gain/1', 'Add_Control/2');
add_line(model_name, 'Add_Control/1', 'Actuator_Saturation/1');
add_line(model_name, 'Actuator_Saturation/1', 'Log_Force/1');
add_line(model_name, 'Actuator_Saturation/1', 'Nonlinear_Derivatives/1');
add_line(model_name, 'Disturbance_Kick/1', 'Nonlinear_Derivatives/2');

% Continuous Integration loop (Zero Direct-Feedthrough Integrator)
add_line(model_name, 'Nonlinear_Derivatives/1', 'Continuous_Integrator/1');
add_line(model_name, 'Continuous_Integrator/1', 'Nonlinear_Derivatives/3');
add_line(model_name, 'Continuous_Integrator/1', 'State_Demux/1');
add_line(model_name, 'Continuous_Integrator/1', 'Log_States/1');

% Sensor noise & ADC sampling
add_line(model_name, 'Noise_Pos/1', 'Add_Noise_Pos/1');
add_line(model_name, 'State_Demux/1', 'Add_Noise_Pos/2');
add_line(model_name, 'Add_Noise_Pos/1', 'Mux_Meas/1');

add_line(model_name, 'State_Demux/3', 'Add_Noise_Ang/1');
add_line(model_name, 'Noise_Ang/1', 'Add_Noise_Ang/2');
add_line(model_name, 'Add_Noise_Ang/1', 'Mux_Meas/2');

add_line(model_name, 'Mux_Meas/1', 'ZOH_ADC/1');

% Discrete feedback loops (Broken via Unit Delay)
add_line(model_name, 'ZOH_ADC/1', 'Discrete_EKF_Observer/1');
add_line(model_name, 'Actuator_Saturation/1', 'Unit_Delay_U/1');
add_line(model_name, 'Unit_Delay_U/1', 'Discrete_EKF_Observer/2');
add_line(model_name, 'Discrete_EKF_Observer/1', 'Log_EKF/1');
add_line(model_name, 'Discrete_EKF_Observer/1', 'LQR_K_Gain/1');

%% 10. SAVE SIMULINK MODEL TO DISK
save_system(model_name);
fprintf('4/4: >> SUCCESS: Model saved to %s.slx (100%% Algebraic Loop-Free).\n', model_name);